#version: '3'  # Docker Compose 文件版本

services:
  geekaiapp:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "15001:15001"
#      - '${PORT:-15001}:15001'
    env_file:
      - .env
#  jimeng_video_service:
#    build: .
#    volumes:
#      - .:/app
#    working_dir: /app
#    ports:
#      - "15100:15100"
#    env_file:
#      - .env
#  yewu2googleimgtxt:
#    build: .
#    volumes:
#      - .:/app
#    working_dir: /app
#    ports:
#      - "15101:15101"
#    env_file:
#      - .env
  yewu2story:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "15102:15102"
    env_file:
      - .env
  yewu2edgetts:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "15103:15103"
    env_file:
      - .env
#  yewu2excelhtml:
#    build: .
#    volumes:
#      - .:/app
#    working_dir: /app
#    ports:
#      - "15104:15104"
#    env_file:
#      - .env
#  yewu2videoaddsrt:
#    build: .
#    volumes:
#      - .:/app
#    working_dir: /app
#    #    command: python geekaiapp/g_jiekou.py
#    ports:
#      - "15114:15114"
#    env_file:
#      - .env
#  db1student:
#    build: .
#    volumes:
#      - .:/app
#    working_dir: /app
#    #    command: python geekaiapp/g_jiekou.py
#    ports:
#      - "15105:15105"
#    env_file:
#      - .env
